<?php
echo $this->flashMessenger()
        ->setMessageOpenFormat("<div %s>")
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button></div>')
        ->render('success',array('alert alert-success'));

echo $this->flashMessenger()
        ->setMessageOpenFormat("<div %s>")
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button></div>')
        ->render('error',array('alert alert-danger'));

?>

<a class="btn btn-success" href="<?php echo $this->url('categoria/default', array('controller' => 'categoria')); ?>">Categoria</a>
<br/><br/>
<a class="btn btn-success" href="<?php echo $this->url('post/default', array('controller' => 'post')); ?>">Post</a>
<br/><br/>



<a class="btn btn-success" href="<?php echo $this->url('home/default', array('controller' => 'home', 'action' => 'debug')); ?>">Debug</a>
<br/><br/>
<br/><br/>
<br/><br/>



<a class="btn btn-success" href="<?php echo $this->url('nivel/default', array('controller' => 'nivel')); ?>">Nivel</a>
<br/><br/>

<a class="btn btn-success" href="<?php echo $this->url('auth/default', array('controller' => 'auth')); ?>">Login</a>
<br/><br/><br/><br/>



<a class="btn btn-success" href="<?php echo $this->url('conta-login/default', array('controller' => 'conta-login')); ?>">Login</a>
<br/><br/>

<?php if ($this->identity()): ?>
<?php //var_dump($this->identity());die; ?>
<?php echo $this->identity()->getNome(); ?><br/>
<?php echo $this->identity()->getLogin(); ?><br/>
<?php echo $this->identity()->getNivel(); ?>
<?php endif; ?>

<br/>
<br/>
<br/>