<?php
if ($this->success) {
    echo '<div class="alert alert-success">' . $this->translate($this->success[0]) . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}

if ($this->error) {
    echo '<div class="alert alert-danger">' . $this->translate($this->error[0]) . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}

if ($this->warning) {
    echo '<div class="alert alert-warning">' . $this->translate($this->warning[0]) . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}
?>

<a class="btn btn-success" href="<?php echo $this->url('nivel/default', array('controller' => 'nivel', 'action' => 'inserir')); ?>"><?php echo $this->translate("Cadastrar"); ?></a>
<br>
<table class="table table-bordered table-striped table-hover table-condensed">
    <caption class="text-center"><?php echo $this->translate("Todas os niveis"); ?></caption>
    <thead>
        <tr>
            <th class="text-uppercase"><?php echo $this->translate("Id"); ?></th>
            <th class="text-uppercase"><?php echo $this->translate("Nome"); ?></th>
            <th class="text-uppercase"><?php echo $this->translate("Acao"); ?></th>
        </tr>

    </thead>
    <tbody>
        <?php
        if ($this->data):
            ?>

            <?php
            foreach ($this->data as $entity):
                ?>


                <tr>
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getNome(); ?></td>
                    <td>
                        <a href="<?php echo $this->url('nivel/default', array('controller' => 'nivel', 'action' => 'editar', 'id' => $entity->getId())); ?>" title="<?php echo $this->translate("Editar"); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a href="<?php echo $this->url('nivel/default', array('controller' => 'nivel', 'action' => 'excluir', 'id' => $entity->getId())); ?>" title="<?php echo $this->translate("Excluir"); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>

        <?php else: ?>

            <tr>
                <td colspan="3"><?php echo $this->translate("Nao foi encontrado nenhum resultado"); ?></td>
            </tr>

        <?php
        endif;
        ?>

    </tbody>



</table>



<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('router' => 'nivel/paginator')); ?>