<?php

echo $this->flashMessenger()
        ->setMessageOpenFormat("<div %s>")
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button></div>')
        ->render('success', array('alert alert-success'));

echo $this->flashMessenger()
        ->setMessageOpenFormat("<div %s>")
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button></div>')
        ->render('error', array('alert alert-danger'));

$form = $this->form;

$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert">x</button>')
        ->setMessageCloseString('</div>')
        ->render($form);


$form->setAttribute('action', $this->url('auth/default', array('controller' => 'auth')));

$form->prepare();

echo $this->form()->openTag($form);
echo '<div class="form-block">';
echo '<div class="container">';

echo '<div class="form-group">';
//echo $this->formRow($form->get('login')->setValue($data['login']));
echo $this->formRow($form->get('login'));
echo '</div>';

echo '<div class="form-group">';
echo $this->formRow($form->get('senha'));
echo '</div>';



echo '<div class="form-group">';
echo $this->formRow($form->get('submit'));
echo '</div>';
echo '</div>';
echo '</div>';
echo $this->form()->closeTag();

/*
  //ou
  echo $this->form()->openTag($form);
  echo $this->formCollection($form);
  echo $this->form()->closeTag();
 */

echo '<br>';
echo '<br>';
echo '<a class="" href="' . $this->url('conta-login/default', array('controller' => 'conta-login')) . '">' . $this->translate("Esqueceu sua senha?") . '</a>';

echo '<br>';
echo '<br>';
echo '<a class="btn btn-success" href="' . $this->url('usuario/default', array('controller' => 'usuario')) . '">' . $this->translate("Lista") . '</a>';
