<?php

namespace Login\Entity;

/**
 * AlterarSenhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlterarSenhaRepository extends \Doctrine\ORM\EntityRepository
{
}
