<?php

namespace Login\Entity;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByLogin($login, $password) {
        /*
          $userLogin = $this->createQueryBuilder('u')
          ->where('u.login = :a1')
          ->setParameter('a1', $login)->getQuery()->getOneOrNullResult();
         * 
         */

        $userLogin = $this->createQueryBuilder('u')
                        ->join('u.login', 'l')
                        ->where('l.login = :a1')
                        ->setParameter('a1', $login)->getQuery()->getOneOrNullResult();


        if (!is_null($userLogin)) {
            if ($userLogin->getLogin()->encryptPassword($password) == $userLogin->getLogin()->getSenha()) {
                //var_dump($userLogin) ;die;
                $session = new Session;
                $session ->setNome($userLogin->getNome());
                $session ->setLogin($userLogin->getLogin()->getLogin());
                $session ->setNivel($userLogin->getNivel()->getId());                         
                return $session;
            }
        }
        return false;
    }
    
    
}
